# CausalXray/environment.yml
name: causalxray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - cudatoolkit=11.6
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - scikit-image>=0.19.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - tensorboard>=2.8.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipywidgets>=7.6.0
  - pytest>=6.2.0
  - pip
  - pip:
    - captum>=0.5.0
    - wandb>=0.12.0
    - pydicom>=2.3.0
    - hydra-core>=1.1.0
    - omegaconf>=2.1.0
    - albumentations>=1.1.0
    - torchmetrics>=0.7.0
    - pytorch-lightning>=1.5.0
