# CausalXray Configuration for RSNA Pneumonia Detection Dataset
experiment_name: "causalxray_rsna"
output_dir: "./experiments"
log_dir: "./logs"
checkpoint_dir: "./checkpoints"
device: "cuda"
random_seed: 42

model:
  backbone: "densenet121"
  pretrained: true
  num_classes: 2
  feature_dims: [1024, 512, 256]
  dropout_rate: 0.3

causal:
  confounders:
    patient_id: 1000  # Anonymized patient identifier
    class_type: 2     # Lung opacity vs pneumonia
  hidden_dims: [512, 256]
  dropout_rate: 0.3
  use_variational: true
  use_domain_adaptation: true
  num_domains: 2
  use_causal_graph: false  # Limited confounder info for RSNA

training:
  batch_size: 32
  num_epochs: 120
  learning_rate: 0.0008
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"
  grad_clip: 1.0

  # Progressive training strategy
  progressive_training: true
  phase_epochs: [40, 40, 40]

  loss_weights:
    classification: 1.0
    disentanglement: 0.25
    domain: 0.15
    attribution: 0.2

  early_stopping: true
  patience: 20
  min_delta: 0.0001

data:
  data_dir: "./data/rsna_pneumonia"
  datasets: ["rsna"]
  image_size: [224, 224]
  normalize: true
  augmentation: true
  num_workers: 4
  pin_memory: true

# Loss configuration
loss:
  focal_alpha: 1.0
  focal_gamma: 2.0
  weights:
    classification: 1.0
    disentanglement: 0.25
    domain: 0.15
    attribution: 0.2

  # Disentanglement loss configuration
  disentanglement:
    beta_vae: 0.8
    independence_weight: 0.1

# Optimizer configuration
optimizer:
  type: "adam"
  lr: 0.0008
  weight_decay: 0.0001
  betas: [0.9, 0.999]

# Scheduler configuration
scheduler:
  enabled: true
  type: "cosine"
  T_max: 120
  eta_min: 0.000001

# Attribution configuration
attribution:
  patch_size: 16
  attribution_methods: ["intervention", "counterfactual", "gradcam"]

# Logging configuration
logging:
  use_tensorboard: true
  use_wandb: false
  wandb_config:
    project: "causalxray"
    tags: ["rsna", "pneumonia", "causal"]
